### PR TITLE
MITO-320 : implement address manager

### PR DESCRIPTION
**Pull request by hashableric**
* add payment event attribute

### CODE REVIEW

**Review by byeongsu-hong — CHANGES_REQUESTED** [review]
can you rename the attribute key to `gas_paid` and move downside?

**Comment by hashableric** [comment]
@byeongsu-hong I match this name with stub from hyperlane agent.

**Comment by byeongsu-hong** [comment]
> @byeongsu-hong I match this name with stub from hyperlane agent.

or at least moving downside

**Comment by hashableric** [comment]
yup wftm

**Review by byeongsu-hong — APPROVED** [review]

**Pull request merged**
